set(WIFI_SSID1 "WIFI_SSID1")
set(WIFI_PASSWORD1 "WIFI_PASSWORD1")
set(WIFI_SSID2 "WIFI_SSID2")
set(WIFI_PASSWORD2 "WIFI_PASSWORD2")
set(PICOW_HOSTNAME "DEFAULT_HOSTNAME")

#For Thingspeak
set(MQTT_CLIENT_ID "MQTT_CLIENT_ID")
set(MQTT_CLIENT_PSW "MQTT_CLIENT_PSW")

